# Generated by Django 4.0.3 on 2022-04-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunyomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunyomi', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'kunyomi',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'meaning',
            },
        ),
        migrations.CreateModel(
            name='Onyomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onyomi', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'onyomi',
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('jlpt', models.IntegerField()),
                ('kunyomis', models.ManyToManyField(related_name='kanji_kunyomi', to='quiz.kunyomi')),
                ('meanings', models.ManyToManyField(related_name='kanji_meaning', to='quiz.meaning')),
                ('onyomis', models.ManyToManyField(related_name='kanji_onyomi', to='quiz.onyomi')),
            ],
            options={
                'db_table': 'kanji',
            },
        ),
    ]
